### ISSUE TITLE
Nodes support

### ISSUE THREAD

**Issue by UnsafePointer** [Ruenzuo/fbsnapfail#2]
Node support hasn't been tested.

This should be pretty straightforward to implement with [`FilePath`](http://javadoc.jenkins-ci.org/hudson/FilePath.html) which is a `File` class with the super powers I need to move files around as if everything was on the same computer.

**Comment by UnsafePointer** [comment]
Problems locating the log file, maybe the plugin code is running at the Jenkins master instance? 

```
ERROR: Step ‘Publish results from FBSnapshotTestCase’ aborted due to exception: 
java.io.FileNotFoundException: /Users/jenkins/Jenkins/workspace/ios-XNGSearch-slave/xcodebuild.log (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileReader.<init>(FileReader.java:72)
    at com.ruenzuo.fbsnapfail.SnapFailPublisher.perform(SnapFailPublisher.java:48)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

**Comment by UnsafePointer** [comment]
This looks interesting: [Making your plugin behave in distributed Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Making+your+plugin+behave+in+distributed+Jenkins)
